### ISSUE TITLE
Create a github workflow to generate files from latest GEDCOM release

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM.io#199]

**Comment by tychonievich** [comment]
Currently my process is

1. Run https://github.com/FamilySearch/GEDCOM/blob/main/build/push_to_gedcomio.py
2. Create PR
3. Manually merge by running https://github.com/FamilySearch/GEDCOM/blob/main/build/push_to_gedcomio.py again
4. Manually create a release on https://github.com/FamilySearch/GEDCOM/ and upload files there too

**Comment by dthaler** [comment]
After investigation, this is already done.
