### ISSUE TITLE
Read/write compatibility requirements

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM.io#31]
Here's my feedback on the initial compatibility guide, which I'm filing in an issue since the guide wasn't done via a pull request where I would have commented on it there...

> READ FAMILYSEARCH GEDCOM FILE
> The vendor needs to demonstrate the ability to read a sample FamilySearch GEDCOM file and display the contents in there own environement.

One of the sample files provided on the tools page is https://gedcom.io/testfiles/gedcom70/minimal70.ged and simply reading that file (which is "a sample FamilySearch GEDCOM file") and displaying the contents is not very interesting from a compatibility perspective.

> WRITE FAMILYSEARCH GEDCOM FILE
> The vendor needs to demonstrate the ability to write a sample FamilySearch GEDCOM file and prove that it can be read by a FamilySearch GEDCOM Compatible product.

Similarly, the ability to write the minimal70.ged file without any real information in it is not very interesting from a compatibility perspective.

In my opinion, a more useful approach would be a score, rather than a binary yes/no.  For example, we might create a somewhat "maximal" file that uses all the standard tags, enum values, etc. in legal ways, specifically reference that file in the requirement, and then provide some scale or metric on how much of the data was preserved after being read (vs being lost).

If an implementation can ONLY read but not write, it might be a bunch of effort to come up with the appropriate score by verifying what was and was not preserved, but it is not impossible.   Desktop applications and some websites on the other hand would want to both read and write, and for that I think it's actually more practical to score Read+Write compliance together.  That is: read the maximal file into a local environment, and then write a GEDCOM file back out of the local environment, verify the result passes a GEDCOM validator (like the one on the Tools page) and compare the output with the original input, which is relatively straightforward to compute a score for (how much info was preserved vs lost) without any manual effort.   (This is similar to what we do with our desktop app in our github CI/CD today.)

That same approach BTW could be used to provide a migration score (read a "maximal" legal GEDCOM 5.5.1 file, write it to FamilySearch GEDCOM 7, and provide an automated score based on the result).

And I posit that there is no demand for some implementation that would want to write but not read GEDCOM 7 (the reverse being much more common), but would be happy to be proven wrong.  If there is such a demand, then I would say the requirement would be to have the implementation generate a file containing as many different tags as it supports (this may be hard to verify so best effort and honor system is probably the only practical way), and then verify it passes an official GEDCOM validator like the one on the Tools page as compliant.   That will still not measure things like use of extension tags that should have been standard tags instead, which I don't know how to score.  Just saying "prove that it can be read by a FamilySearch GEDCOM Compatible product" to me is too open ended because you could have 2 products that are compatible with each other, but nothing else, which isn't very helpful if they are niche products used by largely disjoint communities.

**Comment by dthaler** [comment]
Questions that affect read/write compliance testing:
Q1: is a record that only contains a structure pointing to the structure pointing to it, equivalent to @VOID@?
For example, are the following equivalent:
```
0 @I1@ INDI
1 NAME John /Doe/
1 FAMC @F1@
0 @F1@ FAM
1 CHIL @I1@
```
and
```
0 @I1@ INDI
1 NAME John /Doe/
1 FAMC @VOID@
```
I think the answer is yes.

Q2: When is it ok to remove a structure with @VOID@, such as in the above example?

I think the answer is: only when there are no substructures, AND the existence of the structure does not imply ordering or count (namely `FAMS` and `CHIL` imply ordering and counts).  So I think the above example is also equivalent to just:
```
0 @I1@ INDI
1 NAME John /Doe/
```

Q3: Is there any meaning (or reason to keep) duplicate trees of structures?  For example, is the below equivalent to the first example above?
```
0 @I1@ INDI
1 NAME John /Doe/
1 FAMC @F1@
1 FAMC @F1@
0 @F1@ FAM
1 CHIL @I1@
```

**Comment by tychonievich** [comment]
Q1. Yes, you can remove structures that provide no new information

Q2. Yes, you can remove structures that provide no new information

Q3. You can remove duplicate structures, but note that records with different Xrefs are not trivially mergeable; additional information (such as UIDs or user input) is needed to determine that. 

We should add a note to this in section 1.6 of the specification

**Comment by tychonievich** [comment]
Most topics in this issue have been handled by the above merges. Any remaining issues should be discussed in #48
