### ISSUE TITLE
Sample Files Usefulness

### ISSUE THREAD

**Issue by clarkegj** [FamilySearch/GEDCOM.io#42]
Here are my results testing the available files with MacFamilyTree 10:

escapes.ged: Works, no issues

extension-record.ged: _LOC is not imported, but user is alerted of this behaviour. A future version will be able to import custom structures to user-defined fields

long-url.ged: Works, no issues

maximal70.ged: Several issues: Duplicate PHON and EMAIL tags in Header are unsupported and silently dropped, „STAT CHALLENGED“ unsupported, PHRASE for ASSO is unsupported, OBJE->FILE->MEDI->PHRASE unsupported, PHRASE from SDATE silently dropped…

minimal70.ged: Works, no issues

remarriage1.ged: Works, no issues

remarriage2.ged: Works, no issues

same-sex-marriage.ged: Works, no issues

spaces.ged: Works, no issues (values are considered empty if they are just spaces)

voidptr.ged: @VOID@ is currently considered „not set“. This will change in a subsequent release of MacFamilyTree.

I need to investigate maximal70.ged further – this file is of tremendous help.

Best,
Mendel

**Comment by jl5000** [comment]
The maximal70.ged file reuses the same UID for several records, e.g. `bbcc0025-34cb-4542-8cfb-45ba201c9c2c`. For my purposes this is not sufficient for testing.
