### ISSUE TITLE
TOC for Practices page is not sticky.

### ISSUE THREAD

**Issue by clarkegj** [FamilySearch/GEDCOM.io#5]
I've tried 
       toc_sticky: false and true --- settings at the top of the page.

**Comment by tychonievich** [comment]
There is no current page named "practices", but `pages_/guides.md` has a subtitle "Technical guides and best practices" so perhaps that's what's meant? It's sidebar is a (hand-written) table of contents and it does appear to be sticky, so I think this issue can be closed.
