### ISSUE TITLE
Add a sample GEDZIP file

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM.io#77]

**Comment by emyoulation** [comment]
2 of the sample GEDZIPs should follow the lead of the basic GEDCOM 7 files. 

In the [Example FamilySearch GEDCOM 7.0 Files](https://gedcom.io/tools/#example-familysearch-gedcom-70-files) in the Tools section of the GEDCOM.io site, there are 2 files:

    maximal70.ged
    minimal70.ged

It would be useful to have GEDZIP expansions of both files:

    maximal70.gdz
    minimal70.gdz

The 'minimal.gdz' embedded Media file might be a single text file describing GEDZIPs Media type guidelines. 
The 'maximal.gdz' should have a tiny example of all MIME types specifically mentioned in the specification; including a sample GEDCOM and/or GEDZIP icon in SVG MIME type )

**Comment by dthaler** [comment]
Excellent suggestions.  Currently the pull request doesn't change what's in maximal70.ged (which only has one local file reference to an mp3) and so maximal70.gdz only has an mp3 so far.  I agree other media types would be good to add too.

**Comment by dthaler** [comment]
Also need to add to maximal70.gdz the following referenced in maximal70.ged:
```
2 TRAN media/derived.oga
2 TRAN media/transcript.vtt
```
