### ISSUE TITLE
Request for @ escapes in maximal70.ged

### ISSUE THREAD

**Issue by jl5000** [FamilySearch/GEDCOM.io#92]
It would be useful if the maximal file had examples of @ symbols, both within line values (which already exists), and with @ escapes at the beginning of line values, including on CONT lines. This will be useful for testing purposes.

**Comment by tychonievich** [comment]
We do have a separate file (escapes.ged) that has them. maximal70.ged's stated goal is to use all tags and enumeration values, not to cover everything (escapes, extensions, etc). However, we do agree that having them in maximal70.ged would increase the ease of testing implementations.
