### ISSUE TITLE
Extension YAML file location

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM.io#95]
When an extension structure is being defined, should it be hosted on an external website or hosted in the gedcom.io repository or both?  Currently I don't think there is any guidance and we should probably provide some guidance.

A documented extension tag needs a URI, and we say that URI should be a URL, ideally resolvable to the YAML description (see https://github.com/FamilySearch/GEDCOM/issues/330 and https://github.com/FamilySearch/GEDCOM/pull/350).

If the URI points to an external website, then the question of durability of the URL arises (what happens if the external website goes away in 10 years?)

**Comment by tychonievich** [comment]
We added the URL recommendation before we had the registry. I think we should change that recommendation to be the registry first, with URI-is-URL as a backup.

**Comment by dthaler** [comment]
Discussion 9/28/2023 in GEDCOM meeting:
We want to recommend the registry be the place extensions are hosted, since they have more durability and discoverability across applications.

**Comment by tychonievich** [comment]
> @tychonievich will add an index of URI to YAML URL to the GEDCOM-registries/generated_files section

Added in https://github.com/FamilySearch/GEDCOM-registries/commit/361ba5f95eaf99a0a29bdce0501c45b86368b75f
