### ISSUE TITLE
Listing superstructures of relocated standard structures

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM.io#97]
https://gedcom.io/terms/format has a "superstructures" section per structure.
However a relocated standard structure is supposed to have the same URI as the standard structure, so an extension that has a relocated standard structure can't have a different YAML file.

Should the standard YAML file be updated for each extension that relocates it?
Or is there no way to specify the "superstructures" section, and only rely on the "substructures" section of the extension structure it's relocated under?

**Comment by tychonievich** [comment]
In <https://gedcom.io/terms/format> we have:

> Because new structures may be added over time in any order, x may be a substructure of y if either x’s `superstructures` includes y or y’s `substructures` includes x.

We have `superstructures` to allow extensions to be substructures of standard structures. We have `substructures` to allow extensions to be superstructures of standard structures. For example, an extension individual event would have `g7:record-INDI` in its `superstructures` and `g7:DATE` in its `substructures`, but presumably not have either of the matching entries in the standard structure's YAML.

The YAML format has similar facilities for enumerations (an extension set can include standard values with `enumeration values`, and extension values can be placed in standard sets with `value of`).

Relocated standard structures are usually not needed used under extensions; there the "extension-defined substructures" should cover most cases. But I do think the relocated standard structure idea might need revisiting. By definition they violate normal sub/super rules, but they don't indicate new rules (making validation impossible) and there's currently no way to give similar freedom to extension structures.

**Comment by tychonievich** [comment]
Put another way:

X may be a substructure of Y if any of the following apply:

- X's YAML file has `superstructures` entry with key Y
- Y's YAML file has `substructures` entry with key X
- X is a relocated standard structure (extension tag and standard URI)

**Comment by tychonievich** [comment]
Hm, I think that example needs to be changed. I can't find a way for it to work with a documented extension. If we had

```yaml
extension tags: [_LOC]
substructures:
    "https://gedcom.io/terms/v7/NAME": "{0:1}"
```

then it would be a `g7:NAME` which does not have a `DATE` substructure. On the other hand, if we had instead

```yaml
extension tags: [_LOC]
substructures:
    "https://example.com/LocationName": "{0:1}"
```

then the name should use an extension tag because it's not a standard structure type.

**Comment by dthaler** [comment]
> Hm, I think that example needs to be changed. I can't find a way for it to work with a documented extension.

I agree, I would prefer that that example not be valid.  However, changing it at this point would seem to be a breaking change where an existing valid GEDCOM 7.0 file would become invalid, so wouldn't that change have to wait for next-major?

**Comment by dthaler** [comment]
Discussion 11/16/2023:
* We don't want to invalidate how existing apps use `_LOC` today
* There may be ways to let YAML files specify deep structure organization
  * Either have the type of substructures be cardinality OR map, or
  * Add some other key that contains hierarchical information

**Comment by dthaler** [comment]
Discussion January 4, 2024:
* Example in spec put a standard tag (`NAME`) where it cannot be a `g7:NAME` or any other standard URI but must be an extension URI due to the `DATE` substructure.
* We could deprecate the use of standard tags in extension-defined substructures when they are not identical to the standard definition, but we cannot disallow them as that would be a breaking change.
* Current [YAML syntax](https://gedcom.io/terms/format) does not yet have a way to specific `stdTag` as an extension, we need a way to allow that in order to supper the current example in the spec.
